//! Shared JSON wire protocol types for hwLedger fleet management (FR-FLEET-001..008).
//!
//! Defines serializable types for agent registration, mTLS bootstrapping, heartbeat telemetry,
//! job dispatch, and state reporting. All types round-trip through `serde_json` for the HTTP/2 + JSON wire.

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use thiserror::Error;
use uuid::Uuid;

/// Error type for protocol violations and serialization failures.
#[derive(Debug, Error, Clone, Serialize, Deserialize, PartialEq)]
pub enum ProtoError {
    #[error("serialization error: {reason}")]
    Serialization { reason: String },

    #[error("validation error: {reason}")]
    Validation { reason: String },

    #[error("unsupported version: {version}")]
    UnsupportedVersion { version: String },
}

// ============================================================================
// Agent registration (FR-FLEET-001, FR-FLEET-002)
// ============================================================================

/// Platform metadata reported by an agent at registration.
/// Traces to: FR-FLEET-001
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Platform {
    /// Operating system (e.g., "macos", "linux", "windows").
    pub os: String,
    /// CPU architecture (e.g., "aarch64", "x86_64").
    pub arch: String,
    /// Kernel version (e.g., "24.2.0" on macOS, "6.8.0" on Linux).
    pub kernel: String,
    /// Total system RAM in bytes.
    pub total_ram_bytes: u64,
    /// CPU model string (e.g., "Apple M4 Pro", "Intel Xeon").
    pub cpu_model: String,
}

/// Agent registration request, sent on first contact or when cert expires.
/// Bootstrap token is validated against server's configured list.
/// Traces to: FR-FLEET-001, FR-FLEET-002
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct AgentRegistration {
    /// Unique identifier for this agent (generated by agent via uuid::v4).
    pub agent_id: Uuid,
    /// Hostname of the agent's host machine.
    pub hostname: String,
    /// PEM-encoded PKCS#10 CSR to be signed by the server's CA.
    pub cert_csr_pem: String,
    /// Platform metadata.
    pub platform: Platform,
    /// One-time bootstrap token for validation.
    pub bootstrap_token: String,
}

/// Server's response to agent registration: includes signed cert and CA bundle.
/// Agent persists these to disk for future mTLS connections.
/// Traces to: FR-FLEET-001, FR-FLEET-002
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct RegistrationAck {
    /// The agent's UUID (echoed from request for confirmation).
    pub agent_id: Uuid,
    /// PEM-encoded certificate signed by the server's CA (30-day validity).
    pub assigned_cert_pem: String,
    /// PEM-encoded root CA certificate for client verification.
    pub ca_cert_pem: String,
    /// Server's current time in milliseconds since Unix epoch (for clock skew detection).
    pub server_time_ms: u64,
}

// ============================================================================
// Heartbeat and telemetry (FR-FLEET-001, FR-FLEET-002)
// ============================================================================

/// Telemetry snapshot for a single device at a single instant.
/// Corresponds to `hwledger_probe::cache::Snapshot` but serializable.
/// Traces to: FR-TEL-002
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct TelemetrySnapshot {
    /// Free (unallocated) VRAM in bytes.
    pub free_vram_bytes: u64,
    /// Utilization percentage, 0.0–100.0.
    pub util_percent: f32,
    /// Device temperature in Celsius.
    pub temperature_c: f32,
    /// Power draw in watts.
    pub power_watts: f32,
    /// Capture timestamp in milliseconds since Unix epoch.
    pub captured_at_ms: u64,
}

/// Telemetry report for a single device.
/// Traces to: FR-TEL-002
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct DeviceReport {
    /// Probe backend name (e.g., "nvidia", "amd", "metal", "intel").
    pub backend: String,
    /// Device ID assigned by the backend.
    pub id: u32,
    /// Human-readable device name (e.g., "RTX 4090", "M4 Pro").
    pub name: String,
    /// Optional UUID for remote/fleet identification.
    pub uuid: Option<String>,
    /// Total VRAM in bytes.
    pub total_vram_bytes: u64,
    /// Latest telemetry snapshot (if available).
    pub snapshot: Option<TelemetrySnapshot>,
}

/// Heartbeat message: agent reports its status and device inventory.
/// Sent periodically (default 30s) to update the server's agent registry and device telemetry.
/// Traces to: FR-FLEET-001, FR-FLEET-002
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Heartbeat {
    /// Agent's UUID (must match registered agent or registration is rejected).
    pub agent_id: Uuid,
    /// Uptime in seconds since agent start.
    pub uptime_s: u64,
    /// Enumerated devices with latest telemetry.
    pub devices: Vec<DeviceReport>,
}

// ============================================================================
// Job dispatch and reporting (FR-FLEET-007, FR-FLEET-008)
// ============================================================================

/// Job state machine.
/// Traces to: FR-FLEET-008
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Hash)]
#[serde(rename_all = "PascalCase")]
pub enum JobState {
    /// Job has been created but not yet sent to an agent.
    Pending,
    /// Agent has acknowledged the job and is executing the command.
    Running,
    /// Command completed with exit code 0.
    Succeeded,
    /// Command completed with non-zero exit code or failed to start.
    Failed,
    /// Command did not complete before the deadline.
    TimedOut,
}

impl JobState {
    /// Returns true if the job is in a terminal state.
    pub fn is_terminal(&self) -> bool {
        matches!(self, JobState::Succeeded | JobState::Failed | JobState::TimedOut)
    }
}

/// Job dispatch order sent by the server to an agent.
/// Agent executes the command and reports back via DispatchReport.
/// Traces to: FR-FLEET-008
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct DispatchOrder {
    /// Unique job ID (assigned by server).
    pub job_id: Uuid,
    /// Target agent UUID.
    pub agent_id: Uuid,
    /// Model reference (e.g., "mistral-7b-inst-v0.3.gguf" or "Qwen3.6-A3B").
    pub model_ref: String,
    /// Optional backend hint (e.g., "metal" on Apple Silicon). Agent may override if unavailable.
    pub backend_hint: Option<String>,
    /// Command to execute (e.g., ["llama.cpp", "--model", "model.gguf", ...]).
    pub command: Vec<String>,
    /// Environment variables to pass to the command.
    pub env: BTreeMap<String, String>,
    /// Optional deadline in milliseconds since Unix epoch. Agent cancels if elapsed.
    pub deadline_ms: Option<u64>,
}

/// Job state report sent by agent to server when state changes.
/// Final report includes exit code and log tail for debugging.
/// Traces to: FR-FLEET-008
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct DispatchReport {
    /// Job ID (echoed from the DispatchOrder).
    pub job_id: Uuid,
    /// Agent UUID (echoed for routing).
    pub agent_id: Uuid,
    /// Current job state.
    pub state: JobState,
    /// Timestamp job transitioned to Running state (Unix epoch ms). None until Running.
    pub started_at_ms: Option<u64>,
    /// Timestamp job reached a terminal state (Unix epoch ms). None until terminal.
    pub finished_at_ms: Option<u64>,
    /// Exit code of the command (if terminal). None otherwise.
    pub exit_code: Option<i32>,
    /// Last 4 KB of process output (stdout + stderr interleaved if available).
    pub log_tail: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    // Traces to: FR-FLEET-001
    #[test]
    fn test_platform_serde() {
        let p = Platform {
            os: "macos".to_string(),
            arch: "aarch64".to_string(),
            kernel: "24.2.0".to_string(),
            total_ram_bytes: 16 * 1024 * 1024 * 1024,
            cpu_model: "Apple M4 Pro".to_string(),
        };
        let json = serde_json::to_string(&p).expect("serialize");
        let p2: Platform = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(p, p2);
    }

    // Traces to: FR-FLEET-001
    #[test]
    fn test_agent_registration_serde() {
        let agent_id = Uuid::new_v4();
        let ar = AgentRegistration {
            agent_id,
            hostname: "gpu-box-1".to_string(),
            cert_csr_pem: "-----BEGIN CERTIFICATE REQUEST-----\n...".to_string(),
            platform: Platform {
                os: "linux".to_string(),
                arch: "x86_64".to_string(),
                kernel: "6.8.0".to_string(),
                total_ram_bytes: 64 * 1024 * 1024 * 1024,
                cpu_model: "Intel Xeon".to_string(),
            },
            bootstrap_token: "secret-token-123".to_string(),
        };
        let json = serde_json::to_string(&ar).expect("serialize");
        let ar2: AgentRegistration = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(ar, ar2);
    }

    // Traces to: FR-FLEET-001
    #[test]
    fn test_registration_ack_serde() {
        let agent_id = Uuid::new_v4();
        let ack = RegistrationAck {
            agent_id,
            assigned_cert_pem: "-----BEGIN CERTIFICATE-----\n...".to_string(),
            ca_cert_pem: "-----BEGIN CERTIFICATE-----\n...".to_string(),
            server_time_ms: 1713456000000,
        };
        let json = serde_json::to_string(&ack).expect("serialize");
        let ack2: RegistrationAck = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(ack, ack2);
    }

    // Traces to: FR-TEL-002
    #[test]
    fn test_telemetry_snapshot_serde() {
        let snap = TelemetrySnapshot {
            free_vram_bytes: 8 * 1024 * 1024 * 1024,
            util_percent: 42.5,
            temperature_c: 65.3,
            power_watts: 120.5,
            captured_at_ms: 1713456000000,
        };
        let json = serde_json::to_string(&snap).expect("serialize");
        let snap2: TelemetrySnapshot = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(snap, snap2);
    }

    // Traces to: FR-TEL-002
    #[test]
    fn test_device_report_serde() {
        let report = DeviceReport {
            backend: "nvidia".to_string(),
            id: 0,
            name: "NVIDIA RTX 4090".to_string(),
            uuid: Some("gpu-uuid-123".to_string()),
            total_vram_bytes: 24 * 1024 * 1024 * 1024,
            snapshot: Some(TelemetrySnapshot {
                free_vram_bytes: 20 * 1024 * 1024 * 1024,
                util_percent: 30.0,
                temperature_c: 60.0,
                power_watts: 100.0,
                captured_at_ms: 1713456000000,
            }),
        };
        let json = serde_json::to_string(&report).expect("serialize");
        let report2: DeviceReport = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(report, report2);
    }

    // Traces to: FR-FLEET-002
    #[test]
    fn test_heartbeat_serde() {
        let agent_id = Uuid::new_v4();
        let hb = Heartbeat {
            agent_id,
            uptime_s: 3600,
            devices: vec![DeviceReport {
                backend: "nvidia".to_string(),
                id: 0,
                name: "RTX 4090".to_string(),
                uuid: Some("gpu-0".to_string()),
                total_vram_bytes: 24 * 1024 * 1024 * 1024,
                snapshot: Some(TelemetrySnapshot {
                    free_vram_bytes: 20 * 1024 * 1024 * 1024,
                    util_percent: 25.0,
                    temperature_c: 55.0,
                    power_watts: 80.0,
                    captured_at_ms: 1713456000000,
                }),
            }],
        };
        let json = serde_json::to_string(&hb).expect("serialize");
        let hb2: Heartbeat = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(hb, hb2);
    }

    // Traces to: FR-FLEET-007, FR-FLEET-008
    #[test]
    fn test_dispatch_order_serde() {
        let job_id = Uuid::new_v4();
        let agent_id = Uuid::new_v4();
        let mut env = BTreeMap::new();
        env.insert("MODEL_PATH".to_string(), "/models/mistral.gguf".to_string());
        env.insert("CUDA_VISIBLE_DEVICES".to_string(), "0".to_string());

        let order = DispatchOrder {
            job_id,
            agent_id,
            model_ref: "mistral-7b-inst-v0.3.gguf".to_string(),
            backend_hint: Some("cuda".to_string()),
            command: vec![
                "llama.cpp".to_string(),
                "--model".to_string(),
                "/models/model.gguf".to_string(),
            ],
            env,
            deadline_ms: Some(1713456000000 + 300000),
        };
        let json = serde_json::to_string(&order).expect("serialize");
        let order2: DispatchOrder = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(order, order2);
    }

    // Traces to: FR-FLEET-008
    #[test]
    fn test_dispatch_report_serde() {
        let job_id = Uuid::new_v4();
        let agent_id = Uuid::new_v4();
        let report = DispatchReport {
            job_id,
            agent_id,
            state: JobState::Succeeded,
            started_at_ms: Some(1713456000000),
            finished_at_ms: Some(1713456030000),
            exit_code: Some(0),
            log_tail: "Generated 100 tokens, avg latency 42ms\n".to_string(),
        };
        let json = serde_json::to_string(&report).expect("serialize");
        let report2: DispatchReport = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(report, report2);
    }

    // Traces to: FR-FLEET-008
    #[test]
    fn test_job_state_is_terminal() {
        assert!(!JobState::Pending.is_terminal());
        assert!(!JobState::Running.is_terminal());
        assert!(JobState::Succeeded.is_terminal());
        assert!(JobState::Failed.is_terminal());
        assert!(JobState::TimedOut.is_terminal());
    }

    // Traces to: FR-FLEET-001
    #[test]
    fn test_proto_error_serde() {
        let err = ProtoError::Validation { reason: "missing field".to_string() };
        let json = serde_json::to_string(&err).expect("serialize");
        let err2: ProtoError = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(err, err2);
    }
}
