/**
 * Enriched manifest consumed by the Remotion pipeline. Produced by
 * `hwledger-journey-render` (the Rust CLI wrapper) from the canonical
 * phenotype-journeys manifest + sidecar scene-spec overlay.
 *
 * Shape is a strict superset of the canonical manifest: all base fields
 * carry through; the enrichment adds `scenes[]`, `voiceover` metadata,
 * and `recording_rich` as the output MP4 path.
 */

export type Bbox = [number, number, number, number];

/**
 * Fixed anchor positions for callouts + annotations.
 *
 * `auto` lets the renderer pick based on the annotation's `bbox` anchor
 * (default: `top-right` with offset to the right of the bbox). `custom`
 * requires an explicit `{x,y}` pair via the `custom` field.
 */
export type CalloutPosition =
  | "top-left"
  | "top-right"
  | "bottom-left"
  | "bottom-right"
  | "center"
  | "center-bottom"
  | "center-top"
  | "custom"
  | "auto";

export interface Annotation {
  bbox: Bbox;
  label: string;
  color?: string | null;
  style?: "solid" | "dashed";
  note?: string | null;
  kind?: "region" | "pointer" | "highlight";
  /** Where to anchor the callout for this annotation. Defaults to `auto`. */
  position?: CalloutPosition;
  /** When `position = "custom"`, pixel-space coords of the callout origin. */
  custom?: { x: number; y: number };
}

/** Cursor track sample — one point per captured frame. */
export interface CursorPoint {
  /** Frame index in the rendered composition. */
  frame: number;
  x: number;
  y: number;
  /** True when a click fires on this frame (triggers a ripple pulse). */
  click?: boolean;
}

export interface JourneyStep {
  index: number;
  slug: string;
  intent: string;
  screenshot_path: string;
  description?: string | null;
  blind_description?: string | null;
  annotations?: Annotation[] | null;
}

export interface SceneSpec {
  /** Which step (by index) this scene annotates. */
  step: number;
  /** Title-style callout shown top-right (spring-animated). */
  calloutText: string;
  /** Optional second line under the callout. */
  calloutSubText?: string;
  /** Accent colour of the callout border + title. */
  calloutColor?: string;
  /** Frames to hold this scene (at 30 fps). Default 90 (3s). */
  durationFrames?: number;
}

export interface VoiceoverSpec {
  /**
   * Voiceover backend used to synthesise `audio`.
   *   - `silent`    = no audio track
   *   - `piper`     = locally synthesised with Piper
   *   - `edge-tts`  = synthesised via Microsoft edge-tts (cloud)
   *   - `edge`      = alias of `edge-tts`
   */
  backend: "silent" | "piper" | "edge-tts" | "edge";
  /** Per-scene narration text (index-aligned with `scenes`). */
  lines?: string[];
  /** Relative path to a pre-rendered WAV/MP3 under `public/`. */
  audio?: string | null;
}

export interface RichManifest {
  id: string;
  intent: string;
  recording?: string | null;
  recording_gif?: string | null;
  /** Path to the enriched MP4 rendered by Remotion. */
  recording_rich?: string | null;
  keyframe_count: number;
  passed: boolean;
  steps: JourneyStep[];
  /** Scene overlays (callouts, captions) for the rich render. */
  scenes?: SceneSpec[];
  voiceover?: VoiceoverSpec;
  /** File list of annotated PNG keyframes generated by `annotate.ts`. */
  annotated_keyframes?: string[];
  /**
   * Per-scene cursor track emitted by Playwright / GUI recorders. When
   * present, Remotion renders a cursor dot + click-pulse overlay aligned to
   * these coordinates (no-op when empty).
   */
  cursor_track?: CursorPoint[];
}

export interface CalloutProps {
  text: string;
  subText?: string;
  color: string;
  startFrame: number;
  /**
   * Where to anchor the callout. Default: `top-right` (legacy behaviour).
   *
   * @example
   * ```tsx
   * <Callout at="center-bottom" from={0} to={90} label="Click Plan" />
   * ```
   */
  at?: CalloutPosition;
  /** When `at = "custom"`, absolute pixel coords of the anchor. */
  custom?: { x: number; y: number };
  /** Optional bbox to circle before showing the callout text. */
  bbox?: Bbox;
  /** Frame the callout disappears at (defaults to hold through end of scene). */
  endFrame?: number;
}

export interface CursorOverlayProps {
  track: CursorPoint[];
  /** Base radius of the cursor dot, in pixels. */
  radius?: number;
  /** Hex colour of the dot. */
  color?: string;
}

export interface FeatureSceneProps {
  videoSrc: string;
  calloutText: string;
  calloutSubText?: string;
  calloutColor: string;
  audioSrc?: string;
  captionText: string;
}
