/**
 * Enriched manifest consumed by the Remotion pipeline. Produced by
 * `hwledger-journey-render` (the Rust CLI wrapper) from the canonical
 * phenotype-journeys manifest + sidecar scene-spec overlay.
 *
 * Shape is a strict superset of the canonical manifest: all base fields
 * carry through; the enrichment adds `scenes[]`, `voiceover` metadata,
 * and `recording_rich` as the output MP4 path.
 */

export type Bbox = [number, number, number, number];

export interface Annotation {
  bbox: Bbox;
  label: string;
  color?: string | null;
  style?: "solid" | "dashed";
  note?: string | null;
  kind?: "region" | "pointer" | "highlight";
}

export interface JourneyStep {
  index: number;
  slug: string;
  intent: string;
  screenshot_path: string;
  description?: string | null;
  blind_description?: string | null;
  annotations?: Annotation[] | null;
}

export interface SceneSpec {
  /** Which step (by index) this scene annotates. */
  step: number;
  /** Title-style callout shown top-right (spring-animated). */
  calloutText: string;
  /** Optional second line under the callout. */
  calloutSubText?: string;
  /** Accent colour of the callout border + title. */
  calloutColor?: string;
  /** Frames to hold this scene (at 30 fps). Default 90 (3s). */
  durationFrames?: number;
}

export interface VoiceoverSpec {
  /** "silent" = skip TTS; "piper" = locally synthesised with Piper. */
  backend: "silent" | "piper";
  /** Per-scene narration text (index-aligned with `scenes`). */
  lines?: string[];
  /** Relative path to a pre-rendered WAV/MP3 under `public/`. */
  audio?: string | null;
}

export interface RichManifest {
  id: string;
  intent: string;
  recording?: string | null;
  recording_gif?: string | null;
  /** Path to the enriched MP4 rendered by Remotion. */
  recording_rich?: string | null;
  keyframe_count: number;
  passed: boolean;
  steps: JourneyStep[];
  /** Scene overlays (callouts, captions) for the rich render. */
  scenes?: SceneSpec[];
  voiceover?: VoiceoverSpec;
  /** File list of annotated PNG keyframes generated by `annotate.ts`. */
  annotated_keyframes?: string[];
}

export interface CalloutProps {
  text: string;
  subText?: string;
  color: string;
  startFrame: number;
}

export interface FeatureSceneProps {
  videoSrc: string;
  calloutText: string;
  calloutSubText?: string;
  calloutColor: string;
  audioSrc?: string;
  captionText: string;
}
