//! `user-story-docs` — auto-doc generator for harvested user-stories.
//!
//! Reads the JSON index produced by
//! `tools/user-story-extract/` (default path:
//! `docs-site/quality/user-stories.json`) and, for each story, renders a
//! `docs-site/journeys/<id>.md` page.
//!
//! The page layout is:
//! ```md
//! # <title>
//!
//! <persona prose>
//!
//! ## Given
//! <given prose>
//!
//! ## When
//! - <when step 1>
//! - <when step 2>
//!
//! ## Then
//! - <then assertion 1>
//!
//! <RecordingEmbed tape="<id>" kind="<family>" />
//! <KeyframeGallery journeyId="<id>" />
//!
//! <!-- auto-generated by tools/user-story-docs — DO NOT EDIT above this line -->
//! <!-- @user-story-docs:END -->
//!
//! <!-- prose authored here survives regeneration -->
//! ```
//!
//! The block up to and including `@user-story-docs:END` is fully overwritten
//! each run. Any prose *after* the marker is preserved byte-for-byte.

use serde::{Deserialize, Serialize};
use std::fs;
use std::path::{Path, PathBuf};
use thiserror::Error;

/// Single harvested user-story. This mirrors a subset of
/// `user_story_extract::UserStory` — we re-declare it here to avoid a hard
/// workspace dep on the harvester crate (the two live in the same workspace
/// but user-story-extract is in a sibling worktree and may not be a member
/// of every checkout yet).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserStory {
    pub journey_id: String,
    pub title: String,
    pub persona: String,
    pub given: String,
    pub when: Vec<String>,
    pub then: Vec<String>,
    pub traces_to: Vec<String>,
    #[serde(default)]
    pub family: Option<String>,
    #[serde(default)]
    pub record: Option<bool>,
    #[serde(default)]
    pub source_file: Option<String>,
}

/// Top-level shape of `docs-site/quality/user-stories.json`.
#[derive(Debug, Clone, Deserialize)]
#[serde(untagged)]
pub enum Index {
    /// Bare list of stories.
    List(Vec<UserStory>),
    /// Wrapped `{ "stories": [...] }`.
    Wrapped {
        #[serde(default)]
        stories: Vec<UserStory>,
    },
}

impl Index {
    pub fn into_stories(self) -> Vec<UserStory> {
        match self {
            Index::List(v) => v,
            Index::Wrapped { stories } => stories,
        }
    }
}

#[derive(Debug, Error)]
pub enum DocsError {
    #[error("io error at {path}: {source}")]
    Io {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("json parse error in {path}: {source}")]
    Json {
        path: PathBuf,
        #[source]
        source: serde_json::Error,
    },
}

pub const END_MARKER: &str = "<!-- @user-story-docs:END -->";
const TOP_MARKER: &str =
    "<!-- auto-generated by tools/user-story-docs — DO NOT EDIT above this line -->";

/// Render the auto-generated header for a single story. This is exactly the
/// block that gets overwritten on every run (top → `END_MARKER` inclusive).
pub fn render_auto_block(story: &UserStory) -> String {
    let family = story.family.as_deref().unwrap_or("other");

    let mut out = String::new();
    out.push_str(&format!("# {}\n\n", story.title));
    out.push_str(&format!("{}\n\n", story.persona));

    out.push_str("## Given\n\n");
    out.push_str(&format!("{}\n\n", story.given.trim()));

    out.push_str("## When\n\n");
    for w in &story.when {
        out.push_str(&format!("- {}\n", w));
    }
    out.push('\n');

    out.push_str("## Then\n\n");
    for t in &story.then {
        out.push_str(&format!("- {}\n", t));
    }
    out.push('\n');

    if !story.traces_to.is_empty() {
        out.push_str("## Traces to\n\n");
        for fr in &story.traces_to {
            out.push_str(&format!("- `{}`\n", fr));
        }
        out.push('\n');
    }

    out.push_str(&format!(
        "<RecordingEmbed tape=\"{}\" kind=\"{}\" />\n",
        story.journey_id, family
    ));
    out.push_str(&format!(
        "<KeyframeGallery journeyId=\"{}\" />\n\n",
        story.journey_id
    ));

    out.push_str(TOP_MARKER);
    out.push('\n');
    out.push_str(END_MARKER);
    out.push('\n');
    out
}

/// Compose the final file content for a given story.
///
/// If `existing_prose` is `Some`, it's appended verbatim after the end
/// marker (newline already included in the auto block). Otherwise a single
/// seed comment is appended so human editors know where to write.
pub fn compose_page(story: &UserStory, existing_prose: Option<&str>) -> String {
    let mut out = render_auto_block(story);
    match existing_prose {
        Some(prose) if !prose.is_empty() => {
            // Preserve whatever was below the marker byte-for-byte, including
            // its own leading newline if present.
            if !prose.starts_with('\n') {
                out.push('\n');
            }
            out.push_str(prose);
        }
        _ => {
            out.push_str(
                "\n<!-- Prose authored here survives regeneration. Add journey context below. -->\n",
            );
        }
    }
    out
}

/// Given a previous file body, return only the prose AFTER `END_MARKER`
/// (stripped of the marker line itself). Returns `None` if the marker is
/// absent (either the file is brand new or manually authored without us).
pub fn extract_preserved_prose(previous: &str) -> Option<&str> {
    let idx = previous.find(END_MARKER)?;
    let after = &previous[idx + END_MARKER.len()..];
    // Consume exactly one trailing newline after the marker if present, so
    // we don't accumulate blank lines across regenerations.
    let after = after.strip_prefix('\n').unwrap_or(after);
    Some(after)
}

/// Per-file generation decision.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PlannedAction {
    Create,
    Update,
    Unchanged,
}

#[derive(Debug, Clone)]
pub struct PlannedWrite {
    pub path: PathBuf,
    pub action: PlannedAction,
    pub new_content: String,
    pub old_content: Option<String>,
}

/// Plan a regeneration pass: read (if present) the prior file for each
/// story and determine what would change. Does not touch disk.
pub fn plan(stories: &[UserStory], output_dir: &Path) -> Result<Vec<PlannedWrite>, DocsError> {
    let mut out = Vec::new();
    for story in stories {
        let path = output_dir.join(format!("{}.md", story.journey_id));
        let (old, existing_prose_owned): (Option<String>, Option<String>) = if path.exists() {
            let body = fs::read_to_string(&path).map_err(|e| DocsError::Io {
                path: path.clone(),
                source: e,
            })?;
            let prose = extract_preserved_prose(&body).map(|s| s.to_string());
            (Some(body), prose)
        } else {
            (None, None)
        };
        let new_content = compose_page(story, existing_prose_owned.as_deref());
        let action = match &old {
            None => PlannedAction::Create,
            Some(prev) if *prev == new_content => PlannedAction::Unchanged,
            Some(_) => PlannedAction::Update,
        };
        out.push(PlannedWrite {
            path,
            action,
            new_content,
            old_content: old,
        });
    }
    Ok(out)
}

/// Apply a planned write set to disk.
pub fn apply(plans: &[PlannedWrite]) -> Result<usize, DocsError> {
    let mut written = 0;
    for p in plans {
        if matches!(p.action, PlannedAction::Unchanged) {
            continue;
        }
        if let Some(parent) = p.path.parent() {
            if !parent.exists() {
                fs::create_dir_all(parent).map_err(|e| DocsError::Io {
                    path: parent.to_path_buf(),
                    source: e,
                })?;
            }
        }
        fs::write(&p.path, &p.new_content).map_err(|e| DocsError::Io {
            path: p.path.clone(),
            source: e,
        })?;
        written += 1;
    }
    Ok(written)
}

/// Produce a unified-style diff line summary suitable for dry-run output.
/// Returns a vec of lines (caller prints). Kept simple (no external diff
/// crate dep): reports per-file "+N/-M" and a sample of the first differing
/// line.
pub fn summarise_diff(plans: &[PlannedWrite]) -> Vec<String> {
    let mut out = Vec::new();
    for p in plans {
        match p.action {
            PlannedAction::Create => out.push(format!("CREATE {}", p.path.display())),
            PlannedAction::Update => {
                let (added, removed) = count_changed_lines(
                    p.old_content.as_deref().unwrap_or(""),
                    &p.new_content,
                );
                out.push(format!(
                    "UPDATE {}  (+{} / -{} lines)",
                    p.path.display(),
                    added,
                    removed
                ));
            }
            PlannedAction::Unchanged => {}
        }
    }
    out
}

fn count_changed_lines(a: &str, b: &str) -> (usize, usize) {
    let a_lines: std::collections::HashSet<&str> = a.lines().collect();
    let b_lines: std::collections::HashSet<&str> = b.lines().collect();
    let added = b.lines().filter(|l| !a_lines.contains(l)).count();
    let removed = a.lines().filter(|l| !b_lines.contains(l)).count();
    (added, removed)
}

/// Load and deserialize the user-stories index from a path.
pub fn load_index(path: &Path) -> Result<Vec<UserStory>, DocsError> {
    let raw = fs::read_to_string(path).map_err(|e| DocsError::Io {
        path: path.to_path_buf(),
        source: e,
    })?;
    let idx: Index = serde_json::from_str(&raw).map_err(|e| DocsError::Json {
        path: path.to_path_buf(),
        source: e,
    })?;
    Ok(idx.into_stories())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn story_fixture(id: &str) -> UserStory {
        UserStory {
            journey_id: id.to_string(),
            title: format!("Title for {}", id),
            persona: "solo dev on MacBook".into(),
            given: "the ledger is warm and the CLI is on PATH".into(),
            when: vec!["run foo".into(), "wait for bar".into()],
            then: vec!["see baz".into(), "exit 0".into()],
            traces_to: vec!["FR-DEMO-1".into()],
            family: Some("gui".into()),
            record: Some(true),
            source_file: Some("tests/foo.rs".into()),
        }
    }

    #[test]
    fn idempotent_second_run_leaves_content_identical() {
        let tmp = tempfile::tempdir().unwrap();
        let story = story_fixture("demo-1");
        let stories = vec![story];

        let plan1 = plan(&stories, tmp.path()).unwrap();
        assert_eq!(plan1[0].action, PlannedAction::Create);
        apply(&plan1).unwrap();

        let first = fs::read_to_string(tmp.path().join("demo-1.md")).unwrap();

        let plan2 = plan(&stories, tmp.path()).unwrap();
        assert_eq!(
            plan2[0].action,
            PlannedAction::Unchanged,
            "second run should be Unchanged, diff was:\nOLD:\n{}\nNEW:\n{}",
            plan2[0].old_content.as_deref().unwrap_or(""),
            plan2[0].new_content
        );
        // Even if we apply, file byte content should be byte-identical.
        apply(&plan2).unwrap();
        let second = fs::read_to_string(tmp.path().join("demo-1.md")).unwrap();
        assert_eq!(first, second);
    }

    #[test]
    fn prose_after_marker_survives_regeneration() {
        let tmp = tempfile::tempdir().unwrap();
        let story = story_fixture("demo-2");
        let stories = vec![story.clone()];

        apply(&plan(&stories, tmp.path()).unwrap()).unwrap();

        // Simulate a human editor adding prose below the marker.
        let path = tmp.path().join("demo-2.md");
        let mut body = fs::read_to_string(&path).unwrap();
        body.push_str("\n## Notes\n\nThis is hand-written context.\n");
        fs::write(&path, &body).unwrap();

        // Tweak the story to force an update.
        let mut story2 = story.clone();
        story2.title = "Title for demo-2 (v2)".into();
        let plan2 = plan(&[story2], tmp.path()).unwrap();
        assert_eq!(plan2[0].action, PlannedAction::Update);
        apply(&plan2).unwrap();

        let after = fs::read_to_string(&path).unwrap();
        assert!(
            after.contains("Title for demo-2 (v2)"),
            "title should have been updated"
        );
        assert!(
            after.contains("This is hand-written context."),
            "manual prose must survive regeneration, got:\n{}",
            after
        );
    }

    #[test]
    fn extracts_prose_after_marker() {
        let body = format!(
            "# Title\n\nfoo\n\n{}\n\nExtra prose.\n",
            END_MARKER
        );
        let extracted = extract_preserved_prose(&body).unwrap();
        assert!(extracted.starts_with("\nExtra prose"));
    }

    #[test]
    fn render_contains_recording_and_keyframe_components() {
        let s = story_fixture("demo-3");
        let block = render_auto_block(&s);
        assert!(block.contains("<RecordingEmbed tape=\"demo-3\" kind=\"gui\" />"));
        assert!(block.contains("<KeyframeGallery journeyId=\"demo-3\" />"));
        assert!(block.contains("# Title for demo-3"));
        assert!(block.trim_end().ends_with(END_MARKER));
    }

    #[test]
    fn load_index_accepts_list_and_wrapped() {
        let list = r#"[{"journey_id":"a","title":"T","persona":"P","given":"G","when":["w"],"then":["t"],"traces_to":["FR-A"]}]"#;
        let idx: Index = serde_json::from_str(list).unwrap();
        assert_eq!(idx.into_stories().len(), 1);

        let wrapped = r#"{"stories":[{"journey_id":"a","title":"T","persona":"P","given":"G","when":["w"],"then":["t"],"traces_to":["FR-A"]}]}"#;
        let idx: Index = serde_json::from_str(wrapped).unwrap();
        assert_eq!(idx.into_stories().len(), 1);
    }
}
